config/routes.rb
TeAgendamos::Application.routes.draw do

  match 'support' => 'supports#contact'
  match 'login_and_register' => 'users#login_and_register'
  match 'login' => 'users#login'
  match 'register' => 'users#register'
  match 'dashboard' => 'users#dashboard'
  match '/providers/login_and_register' => 'providers#login_and_register'
  
  resources :products
  resources :categories
  
  authenticated :provider do
    root :to => 'providers#dashboard', :as => :provider_root
  end
  authenticated :user do
    root :to => 'users#dashboard', :as => :user_root
  end
  root :to => "home#index"
  devise_for :users
  devise_for :providers
end

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if user_signed_in?
        %a.brand{:href => user_root_path} Te Agendamos
      - elsif provider_signed_in?
        %a.brand{:href => provider_root_path} Te Agendamos
      - else  
        %a.brand{:href => "/"} Te Agendamos
      .nav-collapse
        %ul.nav
          - if user_signed_in?
            %li.active
              %a{:href => user_root_path} Inicio
          - elsif user_signed_in?
            %li.active
              %a{:href => provider_root_path} Inicio
          -else
            %li.active
              %a{:href => "/"} Inicio
            %li
              %a{:href => "/#contact"} Contacto
          %li
            %a{:href => "http://www.sietecumbres.com.co", :target => "_blank"} Conócenos
      .nav-collapse-right
        %ul.nav
          - if user_signed_in?
            %li
              = link_to('Editar', edit_user_registration_path)
            %li
              = link_to('Salir', destroy_user_session_path, :method=>'delete')
          - elsif provider_signed_in?
            %li
              = link_to('Editar', edit_provider_registration_path)
            %li
              = link_to('Salir', destroy_provider_session_path, :method=>'delete')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Te Agendamos"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer